### ISSUE TITLE
Replace riviera with Go SDK for Azure in Resource Group code

### ISSUE THREAD

**Issue by whiskeyjay** [azdevops/terraform#40]

**Comment by whiskeyjay** [comment]
The Resource Group resource is still using Riviera SDK:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_resource_group.go

**Comment by jen20** [comment]
This is a good idea - Riviera was intended as a stop gap until Microsoft produced a usable SDK. While they might not have done that, it's not really my problem anymore and I don't particularly want to maintain Riviera going forward.

**Comment by sebastus** [comment]
Let's close this issue and open a set of more granular issues - where each addresses a single resource type.
