### ISSUE TITLE
hashicorp#11821 Azure Example fails when augmenting it with count to support VM scaling

### ISSUE THREAD

**Issue by azdevops** [azdevops/terraform#6]
BLOCKED: Asked Tom/Paul
❗️P0 - Blocked with no work-around

hashicorp#11821 Azure Official Example fails when augmenting it with a count logic to support VM scaling.

Related to 6516?

**Comment by StephenWeatherford** [comment]
Customer considers the main issue fixed

> ok I tested and it is working fine.
> One very minor issue though.
> the plan command shows 4 resources to be added BUT the summary tells us 8
